// Tarot Card Data — All 78 Rider-Waite Cards
// Sources: "The Ultimate Guide to Tarot" by Liz Dean
// Images: Public domain Rider-Waite-Smith deck (1909), Pamela Colman Smith


export type TarotSuit = "Major Arcana" | "Cups" | "Pentacles" | "Swords" | "Wands";

export interface TarotCard {
  id: string;
  name: string;
  number: string;
  suit: TarotSuit;
  element?: string;
  planet?: string;
  zodiac?: string;
  keywords: string[];
  upright: string;
  reversed: string;
  description: string;
  wisdomMessage: string;
  imageUrl: string;
}

export const tarotCards: TarotCard[] = [
  // ═══════════════════════════════════════
  // MAJOR ARCANA (22 cards)
  // ═══════════════════════════════════════
  {
    id: "major_00_fool",
    name: "The Fool",
    number: "0",
    suit: "Major Arcana",
    element: "Air",
    planet: "Uranus",
    keywords: ["Beginnings", "Innocence", "Risk", "Adventure", "Freedom"],
    upright: "The Fool heralds new beginnings and calculated risk. It is never too late to begin anew and follow your heart's desire. The journey ahead is not without danger, but it is time to take a leap of faith. This card augurs well for those embarking on new enterprises and educational courses, provided sensible planning is in place; this is a time for optimism and a fresh perspective. Whatever you start now will go well, provided you do look before you leap.",
    reversed: "The Fool reversed brings out the irresponsible side — the mouth works ahead of the brain. Without thinking through the downsides, decisions are made that are not wise. Think carefully before agreeing to a new approach to work and hold back from emotional commitments until you are sure of your ground.",
    description: "The Fool is the innocent adventurer, about to begin an important journey. With a head full of hope, he is idealistic rather than practical. The little dog at his heels tries to warn him of impending peril, but the Fool is blissfully ignorant of the risk he takes in stepping off a cliff.",
    wisdomMessage: "Leap, but look first.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_00_fool_b0379748.jpg",
  },
  {
    id: "major_01_magician",
    name: "The Magician",
    number: "I",
    suit: "Major Arcana",
    element: "Air",
    planet: "Mercury",
    keywords: ["Action", "Creativity", "Willpower", "Manifestation", "Skill"],
    upright: "It's time for action — for communicating and expressing your ideas and desires. This is the card of the inventor, the traveler, the self-employed, and the entrepreneur, as it beckons you to broaden your horizons. You will have the drive to spur your plans forward. Blessed with a magic wand, you have the ability to transform whatever you choose. He directs you to make the most of your skills and talents and step into your power.",
    reversed: "When reversed, the Magician turns trickster — this card can show you being misled by a charming manipulator. What you see is not what you get, and it's all show, not truth. In your projects, the Magician reversed can show a creative block as you feel torn between two paths. It's time to choose one option and commit to it fully.",
    description: "A Magician in action, complete with magic wand and the implements of his trade: the suit symbols of the Pentacle, Cup, Sword, and Wand, representing the four elements. With these base materials, he sets an intention to transmute them. As the conduit between earth and heaven, the Magician stands for decisions and creativity.",
    wisdomMessage: "Manifest your desires.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_01_magician_094854dc.jpg",
  },
  {
    id: "major_02_high_priestess",
    name: "The High Priestess",
    number: "II",
    suit: "Major Arcana",
    element: "Water",
    planet: "The Moon",
    keywords: ["Secrets", "Intuition", "Wisdom", "Mystery", "Spirituality"],
    upright: "Hidden knowledge, intuition, psychic experience, and significant dreams are the gifts of the High Priestess. This is a time for incubation and privacy, to go inward, deepening your relationship with your higher self and trusting your internal knowing. In your everyday life, confidentiality is key. On your spiritual path, the High Priestess predicts learning and a mentor.",
    reversed: "When reversed, the High Priestess can show an inappropriate mentor or choosing a temporarily wrong path. You might be listening to bad advice or someone might try to persuade you to go against your intuition. It can also indicate secrets that need to be out in the open.",
    description: "The High Priestess stands between two great pillars labeled B and J. Behind her is a veil decorated with pomegranates; she wears a horned moon headdress and holds a scroll bearing the letters of the Torah. She represents the principle of the divine feminine — the psychic, astrologer, or spiritual teacher.",
    wisdomMessage: "Explore your spiritual side.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_02_high_priestess_9497593e.jpg",
  },
  {
    id: "major_03_empress",
    name: "The Empress",
    number: "III",
    suit: "Major Arcana",
    element: "Earth",
    planet: "Venus",
    keywords: ["Abundance", "Fertility", "Creativity", "Nurturing", "Nature"],
    upright: "The gifts of the Empress are abundance and material comfort, sensuality and security, and emotional support. This is an auspicious card for children and families, showing harmony at home. Your creative projects thrive and you prosper financially. The Empress is resourceful, so when she appears in your reading, you can feel assured that your needs will be met.",
    reversed: "When reversed, the Empress shows financial issues and domestic strife. She can also show a creative block in your projects and someone who is needy and takes too much from you. There may be an impact on fertility — literally in terms of conceiving a child or figuratively in terms of finding the time and peace of mind to grow an idea.",
    description: "The Empress is the mother archetype, symbol of creativity and abundance. She bears the symbol of Venus on her shield. Seated in an earthly paradise where corn grows at her feet, she represents the solar, earthly, and fertile aspect of womanhood.",
    wisdomMessage: "Life is abundant.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_03_empress_60df74c2.jpg",
  },
  {
    id: "major_04_emperor",
    name: "The Emperor",
    number: "IV",
    suit: "Major Arcana",
    element: "Fire",
    zodiac: "Aries",
    keywords: ["Authority", "Structure", "Control", "Stability", "Leadership"],
    upright: "The Emperor can denote a powerful man and the traditional aspects of rulership and ambition. He brings balance, security, and conventional values. He reveals mastery of life and control over territory, and predicts that problems can be overcome with careful planning and single-mindedness. He shows a return to order — a welcome sign of improvement in your circumstances.",
    reversed: "When reversed, the Emperor is power-hungry and excessive in his demands, representing the negative traits of traditional masculinity — domineering, controlling, and even cruel. The reversed Emperor does not know where to draw the line and may use excessive force to get what he wants.",
    description: "The Emperor is the father archetype, a symbol of male power and virility. He sits squarely on his throne of stone in a landscape of barren rock, yet the mountains protect him. A tiny river runs behind him — a sign of the potential for growth as he directs.",
    wisdomMessage: "Take control; you are protected.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_04_emperor_be082503.jpg",
  },
  {
    id: "major_05_hierophant",
    name: "The Hierophant",
    number: "V",
    suit: "Major Arcana",
    element: "Earth",
    zodiac: "Taurus",
    keywords: ["Education", "Tradition", "Spirituality", "Unity", "Guidance"],
    upright: "The Hierophant shows support, self-realization, and expansion. This is a time to develop emotionally and spiritually — to commit to relationships; to think and philosophize; and to become more spiritually aware. He offers an opportunity to integrate mind and spirit. He also represents good judgment and fairness: the Hierophant asks you to tune your moral compass.",
    reversed: "When reversed, the Hierophant shows poor leadership. You may be misled by an incompetent or egotistic individual at work or on your spiritual path. This is the card of the bad guru — the judgmental teacher who is more interested in furthering his ambitions than supporting you in yours.",
    description: "The Hierophant appears as a figure of religious orthodoxy. Wearing the papal crown and holding the scepter, he makes the hand gesture of blessing to two supplicants kneeling before him. He is the bridge between heaven and earth, the leader who officiates at weddings and guides spiritual seekers.",
    wisdomMessage: "Make the most of your gifts.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_05_hierophant_a9fb5349.jpg",
  },
  {
    id: "major_06_lovers",
    name: "The Lovers",
    number: "VI",
    suit: "Major Arcana",
    element: "Air",
    zodiac: "Gemini",
    keywords: ["Love", "Relationships", "Choices", "Harmony", "Alignment"],
    upright: "The Lovers show relationships and a decision. The card can predict meeting a new partner or a career opportunity, and your choice now will have a significant effect on your future. The person coming into your orbit now has a positive influence and offers true love — provided you follow the guidance of your heart rather than your head. Whatever your situation, the message is to follow your heart's desire.",
    reversed: "When the Lovers card reverses, relationships go out of balance. A relationship is in crisis, and you may question your initial attraction as the values you once held as a couple feel corrupted. There may be inequality, betrayal, and dishonesty.",
    description: "Two Lovers arrive in a magical garden where Archangel Raphael, angel of love and healing, presides over their union. They stand in the Garden of Eden — the woman gazing up at the angel, the man gazing at the woman. The clouds between them predict the hurdles they will overcome as their relationship becomes grounded in reality.",
    wisdomMessage: "Follow the wisdom of your heart.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_06_lovers_1669f82f.jpg",
  },
  {
    id: "major_07_chariot",
    name: "The Chariot",
    number: "VII",
    suit: "Major Arcana",
    element: "Water",
    zodiac: "Cancer",
    keywords: ["Victory", "Determination", "Control", "Journey", "Willpower"],
    upright: "The Chariot signifies success and a major departure. This is a time for determination and focus as you travel in a new direction. A decision is made, and now you can begin to experience real progress in your affairs. Ready to take control and navigate your path, you are poised to learn as your horizons rapidly expand. Financially, you are on the road to success.",
    reversed: "When reversed, there is arrogance and self-indulgence. This can show a person or event spiraling out of control. Ego is at work, and selfish needs come before the greater good. Travel plans and house moves are disrupted or delayed.",
    description: "The Chariot — or the charioteer — stands strong in his carriage of stone, flanked by two resting sphinxes. With the city and its river behind him, he is about to move on. With determination and self-control, he will keep his vehicle on the road and be successful in his quest.",
    wisdomMessage: "Take charge and reach for the stars.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_07_chariot_2da3e91a.jpg",
  },
  {
    id: "major_08_strength",
    name: "Strength",
    number: "VIII",
    suit: "Major Arcana",
    element: "Fire",
    zodiac: "Leo",
    keywords: ["Courage", "Patience", "Endurance", "Compassion", "Inner Strength"],
    upright: "Strength shows that you turn to your higher self for self-guidance. Courage, determination, and patience are needed now, as it is time to get a situation under control. You will need to act with grace and sensitivity, however, rather than using brute force. This is a good card for leadership, as it signifies you are ready to take on a challenge and stand firm.",
    reversed: "When reversed, Strength turns to weakness of will and avoidance of risk, conflicts, and decision-making. This can refer to ignoring your instincts altogether or allowing fear of conflict to stop you from taking action. Whatever you resist persists, so take charge and take on the challenge.",
    description: "A woman in white stands calmly over a lion, holding its jaws open. She stays in control by holding her position, symbolized by the infinity symbol above her head. The lion signifies passion and base instincts, and the woman, civility. She communicates with the lion through her calm presence.",
    wisdomMessage: "With strength, you can discover your higher purpose.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_08_strength_f479acad.jpg",
  },
  {
    id: "major_09_hermit",
    name: "The Hermit",
    number: "IX",
    suit: "Major Arcana",
    element: "Earth",
    zodiac: "Virgo",
    keywords: ["Solitude", "Introspection", "Wisdom", "Guidance", "Inner Search"],
    upright: "There's an opportunity to take time away from routine to consider your options or advance a personal project. The Hermit shows you need more time and space to process your thoughts and feelings. It can show breaking with tradition and finding a unique approach to a challenge. There is also a healing aspect to the Hermit — the card can appear to show self-healing and healing others.",
    reversed: "When reversed, you may be feeling alone and unsupported. However, this is more an attitude than reality, so it's worth asking yourself if you are avoiding help. The card can also show accepting a role — perhaps victim or martyr — that you find hard to let go of due to habit or stubbornness.",
    description: "The Hermit is a man all alone, old and bearded, with just his staff and lantern as his companions in a snowy wilderness. Inside his lantern is a glowing star, a symbol of guidance that lights his way ahead. The Hermit needs privacy, time for silence and discretion, so he can think and plan.",
    wisdomMessage: "Live quietly for a time.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_09_hermit_0cc8182c.jpg",
  },
  {
    id: "major_10_wheel_of_fortune",
    name: "Wheel of Fortune",
    number: "X",
    suit: "Major Arcana",
    element: "Fire",
    planet: "Jupiter",
    keywords: ["Fate", "Change", "Luck", "Cycles", "Destiny"],
    upright: "When the Wheel is upright, anything is possible — and usually positive. Chance meetings, unexpected offers, and news arrive in force. If life has been difficult recently, the Wheel shows a turn for the better. Under this influence, your intuitive powers heighten. This is also an auspicious card for communication with family and friends who live some distance away.",
    reversed: "When the Wheel is reversed, you may suffer some bad luck, but thankfully this marks the end of a run of challenges. The benefits of the upright Wheel will come — it will just take a little longer to gather momentum. On a spiritual level, this card can also show a lack of confidence in your intuitive messages.",
    description: "Flanked by three animals and a winged figure, the Wheel appears between the clouds in blue sky, symbolizing hope, clarity, and a breakthrough on a spiritual path. With the Wheel in motion, destiny is at work: Divine law rules.",
    wisdomMessage: "Surrender to fate.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_10_wheel_of_fortune_12de8620.jpg",
  },
  {
    id: "major_11_justice",
    name: "Justice",
    number: "XI",
    suit: "Major Arcana",
    element: "Air",
    zodiac: "Libra",
    keywords: ["Balance", "Fairness", "Truth", "Law", "Cause and Effect"],
    upright: "There will be a positive outcome. This is a time when past errors or imbalances can be redressed. You benefit from a fair system, provided you are accountable, honest, and deserving. In legal matters, a decision is made or a ruling given, which goes in your favor. On a spiritual level, Justice shows the working out of karma, or actions and consequences.",
    reversed: "When reversed, Justice shows unfairness and imbalance. Legal matters may not go in your favor, or you may be dealing with a system that is corrupt or biased. It can also indicate that you are not being honest with yourself about a situation.",
    description: "Justice is seated between two pillars on a ceremonial podium. This is the judge, or the virtue Justice personified, holding the traditional symbols of the law — an upright sword in her right hand and the scales in her left. Unlike traditional justice figures, tarot's Justice is not blindfolded. Her vision is clear.",
    wisdomMessage: "Truth will prevail.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_11_justice_9ab98546.jpg",
  },
  {
    id: "major_12_hanged_man",
    name: "The Hanged Man",
    number: "XII",
    suit: "Major Arcana",
    element: "Water",
    planet: "Neptune",
    keywords: ["Suspension", "Sacrifice", "Surrender", "New Perspective", "Waiting"],
    upright: "The Hanged Man shows a time of suspension and waiting. This is a period of voluntary sacrifice that leads to a new perspective. You may need to let go of old patterns or beliefs to move forward. The card suggests that by surrendering control and accepting the present moment, you will gain wisdom and insight that was previously unavailable to you.",
    reversed: "When reversed, the Hanged Man shows resistance to necessary change or sacrifice. You may be clinging to old patterns or refusing to see a situation from a different angle. The delay or stagnation you're experiencing is self-imposed.",
    description: "A man hangs upside-down from a living tree, suspended by one foot. His expression is serene rather than anguished. A halo of light surrounds his head. He has chosen this position — it is a voluntary sacrifice that grants him a new perspective on the world.",
    wisdomMessage: "Let go and gain new perspective.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_12_hanged_man_a252e0b7.jpg",
  },
  {
    id: "major_13_death",
    name: "Death",
    number: "XIII",
    suit: "Major Arcana",
    element: "Water",
    zodiac: "Scorpio",
    keywords: ["Transformation", "Endings", "Change", "Transition", "Renewal"],
    upright: "Death rarely signifies physical death. Instead, it heralds transformation, change, and new beginnings. Something in your life is ending, making way for something new. This transition may be difficult, but it is necessary and ultimately positive. The Death card asks you to release what no longer serves you and embrace the new chapter ahead.",
    reversed: "When reversed, Death shows resistance to necessary change. You may be clinging to the past or refusing to let go of something that has run its course. This resistance is creating stagnation and preventing you from moving forward.",
    description: "Death rides a white horse, carrying a black banner emblazoned with a white rose. Before him, figures from all walks of life — a king, a bishop, a maiden, a child — are prostrate or pleading. In the background, the sun rises between two towers, symbolizing the eternal cycle of endings and beginnings.",
    wisdomMessage: "Embrace transformation and new beginnings.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_13_death_41f6a8a4.jpg",
  },
  {
    id: "major_14_temperance",
    name: "Temperance",
    number: "XIV",
    suit: "Major Arcana",
    element: "Fire",
    zodiac: "Sagittarius",
    keywords: ["Balance", "Moderation", "Patience", "Purpose", "Harmony"],
    upright: "Temperance shows the art of negotiation and balance. This is a time to take the middle path, to blend opposites harmoniously, and to exercise patience. You are being guided to find balance in all areas of your life. The angel of Temperance pours water between two cups, showing the flow of life and the importance of maintaining equilibrium.",
    reversed: "When reversed, Temperance shows imbalance and excess. You may be overindulging in one area of life at the expense of others. There is a need to restore harmony and find the middle ground.",
    description: "An angel stands with one foot on land and one in water, pouring liquid between two golden cups. The angel wears a white robe with a triangle within a square on the chest. Irises bloom nearby, and a path leads to mountains in the background where a golden crown glows.",
    wisdomMessage: "Find the middle path.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_14_temperance_e151ccd8.jpg",
  },
  {
    id: "major_15_devil",
    name: "The Devil",
    number: "XV",
    suit: "Major Arcana",
    element: "Earth",
    zodiac: "Capricorn",
    keywords: ["Bondage", "Materialism", "Shadow Self", "Restriction", "Addiction"],
    upright: "The Devil shows restriction and the shadow side of life. This card can represent unhealthy attachments, addictions, or situations where you feel trapped. However, the chains around the figures' necks are loose — they could remove them if they chose. The Devil asks you to examine what is truly binding you and whether you have more freedom than you realize.",
    reversed: "When reversed, the Devil shows liberation from bondage. You are breaking free from restrictions, addictions, or unhealthy patterns. This is a time of release and reclaiming your power.",
    description: "A horned, winged devil sits on a half-cube, to which two human figures are chained by their necks. The chains are loose enough to remove, suggesting the bondage is self-imposed. The inverted pentagram above the devil's head represents the triumph of matter over spirit.",
    wisdomMessage: "Examine what truly binds you.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_15_devil_e40d4078.jpg",
  },
  {
    id: "major_16_tower",
    name: "The Tower",
    number: "XVI",
    suit: "Major Arcana",
    element: "Fire",
    planet: "Mars",
    keywords: ["Sudden Change", "Upheaval", "Revelation", "Chaos", "Awakening"],
    upright: "The Tower represents sudden, dramatic change and the breakdown of existing structures. While this can be shocking and disruptive, it ultimately leads to illumination and liberation. False beliefs, illusions, or structures built on unstable foundations are being destroyed to make way for truth. After the Tower comes the Star — hope and renewal.",
    reversed: "When reversed, the Tower shows that you are resisting necessary change or that the upheaval is less dramatic than feared. You may be avoiding a crisis that needs to be confronted.",
    description: "A tower is struck by lightning, its crown blown off, and two figures fall headlong from the windows. The tower was built on a rocky cliff — a symbol of ambition built on false premises. The lightning bolt of divine truth has struck, and what was built on illusion must fall.",
    wisdomMessage: "From destruction comes illumination.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_16_tower_31009a1a.jpg",
  },
  {
    id: "major_17_star",
    name: "The Star",
    number: "XVII",
    suit: "Major Arcana",
    element: "Air",
    zodiac: "Aquarius",
    keywords: ["Hope", "Inspiration", "Serenity", "Renewal", "Guidance"],
    upright: "The Star brings hope and guidance after difficulty. This is a time of healing, renewal, and spiritual connection. You are being guided by a higher power and can trust that things are moving in the right direction. The Star asks you to have faith in the future and to allow yourself to be inspired and renewed.",
    reversed: "When reversed, the Star shows a loss of faith or hope. You may be feeling disconnected from your spiritual path or unable to see the light at the end of the tunnel. It is important to reconnect with what inspires you.",
    description: "A naked woman kneels by a pool of water, pouring water from two jugs — one onto the earth, one into the pool. Above her, eight stars shine in the sky, the largest being an eight-pointed star. An ibis perches in a tree nearby. The scene radiates serenity and hope.",
    wisdomMessage: "Have faith — your star is rising.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_17_star_8777959e.jpg",
  },
  {
    id: "major_18_moon",
    name: "The Moon",
    number: "XVIII",
    suit: "Major Arcana",
    element: "Water",
    zodiac: "Pisces",
    keywords: ["Illusion", "Fear", "Subconscious", "Intuition", "Dreams"],
    upright: "The Moon represents a crisis of faith and deep emotions. This is a time when things may not be as they seem, and illusions or fears may be clouding your judgment. The Moon asks you to trust your intuition and navigate through uncertainty with care. Pay attention to your dreams and subconscious messages.",
    reversed: "When reversed, the Moon shows that illusions are being dispelled and clarity is returning. Fears that seemed overwhelming are diminishing, and you are beginning to see the truth of a situation.",
    description: "A full moon shines between two towers, casting its light on a path that winds between a dog and a wolf, past a crayfish emerging from a pool. The moon's face looks down with an expression of mystery. The scene represents the unconscious mind and the realm of dreams.",
    wisdomMessage: "Trust your intuition through the darkness.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_18_moon_7e87c78b.jpg",
  },
  {
    id: "major_19_sun",
    name: "The Sun",
    number: "XIX",
    suit: "Major Arcana",
    element: "Fire",
    planet: "The Sun",
    keywords: ["Joy", "Success", "Vitality", "Clarity", "Optimism"],
    upright: "The Sun brings growth, recovery, and radiant success. This is one of the most positive cards in the tarot, heralding a time of joy, clarity, and achievement. Children, creativity, and new projects flourish under the Sun's influence. This is a time to celebrate your accomplishments and embrace the warmth and abundance of life.",
    reversed: "When reversed, the Sun's energy is temporarily blocked or diminished. You may be experiencing self-doubt or a temporary setback. The joy and success of the upright Sun are still available to you — you just need to clear away what is blocking the light.",
    description: "A large, radiant sun shines in the sky, its rays both straight and wavy. A child rides a white horse, arms outstretched in joy, wearing a wreath of flowers. Behind them, sunflowers bloom over a garden wall. The scene radiates pure happiness and vitality.",
    wisdomMessage: "Let your light shine.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_19_sun_b6d370a3.jpg",
  },
  {
    id: "major_20_judgement",
    name: "Judgement",
    number: "XX",
    suit: "Major Arcana",
    element: "Fire",
    planet: "Pluto",
    keywords: ["Reflection", "Reckoning", "Awakening", "Absolution", "Second Chances"],
    upright: "Judgement calls you to reflect on the past and make peace with it. This is a time of reckoning and awakening — a moment to hear the call of your higher self and respond. Second chances are available to you. The card asks you to release guilt and judgment of yourself and others, and to embrace the possibility of renewal and transformation.",
    reversed: "When reversed, Judgement shows self-doubt and an inability to forgive yourself or others. You may be stuck in the past, unable to move forward. It is time to release old wounds and accept the call to a higher purpose.",
    description: "Archangel Gabriel blows his trumpet from the clouds, awakening the dead who rise from their coffins. Men, women, and children of all ages stretch their arms toward the angel in joy and wonder. The mountains in the background represent the immovable nature of truth.",
    wisdomMessage: "Answer the call of your higher self.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_20_judgement_cc1fdd5a.jpg",
  },
  {
    id: "major_21_world",
    name: "The World",
    number: "XXI",
    suit: "Major Arcana",
    element: "Earth",
    planet: "Saturn",
    keywords: ["Completion", "Integration", "Achievement", "Wholeness", "Travel"],
    upright: "The World represents success and the completion of a major life cycle. You have achieved something significant and can celebrate your accomplishments. This card also heralds the beginning of a new cycle — the end of one journey and the start of another. The World asks you to integrate all you have learned and to step into your full potential.",
    reversed: "When reversed, the World shows that completion is delayed or that you are not fully embracing the success that is available to you. There may be loose ends to tie up before you can truly celebrate your achievement.",
    description: "A dancing figure, draped in a purple sash, is surrounded by a laurel wreath. In each corner of the card, the four fixed signs of the zodiac — the bull, lion, eagle, and angel — look on. The figure holds two wands, dancing in celebration of completion and wholeness.",
    wisdomMessage: "Celebrate your achievements and embrace new beginnings.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/major_21_world_92c91b88.jpg",
  },

  // ═══════════════════════════════════════
  // SUIT OF CUPS (Water / Emotions)
  // ═══════════════════════════════════════
  {
    id: "cups_01_ace",
    name: "Ace of Cups",
    number: "Ace",
    suit: "Cups",
    element: "Water",
    keywords: ["New Love", "Intuition", "Creativity", "Emotional Beginnings", "Abundance"],
    upright: "The Ace of Cups heralds new emotional beginnings — a new love, a new friendship, or a new creative project that fills your heart with joy. This is a time of emotional abundance and spiritual renewal. The cup overflows with divine love and blessings. Open your heart to receive what the universe is offering.",
    reversed: "When reversed, the Ace of Cups shows emotional blockages or the inability to receive love. You may be closing your heart to new experiences or suppressing your feelings.",
    description: "A hand emerges from a cloud, offering a golden cup overflowing with five streams of water. A dove descends, carrying a communion wafer. The cup is adorned with an inverted M, representing the waters of consciousness. Water lilies float below.",
    wisdomMessage: "Open your heart to new love.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_01_ace_d9d51575.jpg",
  },
  {
    id: "cups_02_two",
    name: "Two of Cups",
    number: "2",
    suit: "Cups",
    element: "Water",
    keywords: ["Partnership", "Mutual Attraction", "Connection", "Harmony", "Union"],
    upright: "The Two of Cups represents a new partnership or the deepening of an existing relationship. This is a card of mutual attraction, harmony, and connection. Two people come together in a spirit of equality and respect. This card can indicate a romantic relationship, a business partnership, or a deep friendship.",
    reversed: "When reversed, the Two of Cups shows imbalance or disharmony in a relationship. There may be a lack of reciprocity or a misalignment of values.",
    description: "A man and woman face each other, each holding a cup. Between them, the caduceus of Hermes rises — a winged staff entwined by two serpents — topped by a lion's head. This symbol represents the alchemical marriage of opposites.",
    wisdomMessage: "Honor the sacred bond between you.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_02_two_cea76bb6.jpg",
  },
  {
    id: "cups_03_three",
    name: "Three of Cups",
    number: "3",
    suit: "Cups",
    element: "Water",
    keywords: ["Celebration", "Friendship", "Community", "Joy", "Abundance"],
    upright: "The Three of Cups is a card of celebration, friendship, and community. This is a time to rejoice with those you love, to share your successes, and to enjoy the company of good friends. Creative collaborations flourish, and social gatherings bring joy and renewal.",
    reversed: "When reversed, the Three of Cups can indicate overindulgence, gossip, or superficial socializing. There may be a third party causing disruption in a relationship.",
    description: "Three women dance together in a circle, each raising a golden cup in celebration. They are surrounded by flowers and fruit, symbolizing abundance and the harvest. Their flowing robes in red, white, and orange suggest vitality and joy.",
    wisdomMessage: "Celebrate with those you love.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_03_three_cda03761.jpg",
  },
  {
    id: "cups_04_four",
    name: "Four of Cups",
    number: "4",
    suit: "Cups",
    element: "Water",
    keywords: ["Contemplation", "Apathy", "Reevaluation", "Discontent", "Introspection"],
    upright: "The Four of Cups shows a period of contemplation and introspection. You may be feeling dissatisfied or bored with your current situation, unable to appreciate what you have. A divine hand offers a new cup, but you are so focused inward that you may miss this opportunity. This card asks you to look up and consider what is being offered.",
    reversed: "When reversed, the Four of Cups shows a renewed sense of motivation and clarity. You are emerging from a period of apathy and are ready to engage with life again.",
    description: "A young man sits beneath a tree, arms crossed, contemplating three cups before him. A divine hand emerges from a cloud, offering a fourth cup, but he seems unaware of it. His posture suggests withdrawal and introspection.",
    wisdomMessage: "Look up — opportunity awaits.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_04_four_e5fdd04f.jpg",
  },
  {
    id: "cups_05_five",
    name: "Five of Cups",
    number: "5",
    suit: "Cups",
    element: "Water",
    keywords: ["Loss", "Grief", "Regret", "Disappointment", "Moving On"],
    upright: "The Five of Cups represents loss, grief, and disappointment. You may be mourning something that has ended — a relationship, a dream, or an opportunity. The figure focuses on the three spilled cups, failing to notice the two that remain upright. This card asks you to acknowledge your grief while also recognizing what remains.",
    reversed: "When reversed, the Five of Cups shows that you are beginning to move on from grief and loss. You are turning away from what was lost and focusing on what remains.",
    description: "A cloaked figure stands before three overturned cups, head bowed in sorrow. Behind him, two cups remain standing, but he cannot see them. In the distance, a bridge leads to a castle — the path forward is available, but he must first turn around.",
    wisdomMessage: "Acknowledge your grief, then turn toward what remains.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_05_five_3acee9ca.jpg",
  },
  {
    id: "cups_06_six",
    name: "Six of Cups",
    number: "6",
    suit: "Cups",
    element: "Water",
    keywords: ["Nostalgia", "Childhood", "Innocence", "Reunion", "Harmony"],
    upright: "The Six of Cups is a card of nostalgia, childhood memories, and reunion. This is a time to reconnect with your past — with old friends, family, or the innocent joy of childhood. Someone from your past may reappear. This card also speaks to the importance of giving and receiving with an open heart.",
    reversed: "When reversed, the Six of Cups can indicate being stuck in the past or an idealized view of childhood that prevents you from moving forward.",
    description: "Two children stand in a garden, one offering the other a cup filled with flowers. Five more cups, also filled with white flowers, are arranged around them. The scene has a golden, nostalgic quality, evoking the innocence and simplicity of childhood.",
    wisdomMessage: "Honor the past while embracing the present.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_06_six_13b6ead0.jpg",
  },
  {
    id: "cups_07_seven",
    name: "Seven of Cups",
    number: "7",
    suit: "Cups",
    element: "Water",
    keywords: ["Illusion", "Fantasy", "Choices", "Wishful Thinking", "Imagination"],
    upright: "The Seven of Cups represents a time of many choices, fantasies, and illusions. You may be overwhelmed by options or seduced by unrealistic dreams. This card asks you to discern between what is real and what is fantasy, and to make choices based on clarity rather than wishful thinking.",
    reversed: "When reversed, the Seven of Cups shows greater clarity and the ability to make practical choices. The fog of illusion is lifting.",
    description: "A silhouetted figure gazes at seven cups floating in clouds, each containing a different vision — a castle, a wreath, a dragon, a snake, a human figure, jewels, and a face. The cups represent the many illusions and fantasies that can distract us from reality.",
    wisdomMessage: "Choose wisely — not all that glitters is gold.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_07_seven_b2e2c82d.jpg",
  },
  {
    id: "cups_08_eight",
    name: "Eight of Cups",
    number: "8",
    suit: "Cups",
    element: "Water",
    keywords: ["Abandonment", "Withdrawal", "Seeking", "Disillusionment", "Moving On"],
    upright: "The Eight of Cups shows a willingness to walk away from something that no longer fulfills you. Despite having achieved a degree of success or comfort, you feel called to seek something deeper and more meaningful. This card asks you to have the courage to leave behind what is familiar in pursuit of what truly matters.",
    reversed: "When reversed, the Eight of Cups shows a reluctance to move on or a return to a situation that was left behind. You may be avoiding the deeper search for meaning.",
    description: "A cloaked figure walks away from eight stacked cups, heading toward mountains under a crescent moon. The cups are neatly arranged but incomplete — there is a gap in the arrangement. The figure walks with purpose, seeking something beyond material comfort.",
    wisdomMessage: "Have the courage to seek what truly fulfills you.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_08_eight_ff59b4b5.jpg",
  },
  {
    id: "cups_09_nine",
    name: "Nine of Cups",
    number: "9",
    suit: "Cups",
    element: "Water",
    keywords: ["Contentment", "Satisfaction", "Gratitude", "Wishes Fulfilled", "Pleasure"],
    upright: "The Nine of Cups is the wish card — your heart's desire is coming true. This is a time of contentment, satisfaction, and emotional fulfillment. You have achieved what you set out to accomplish, and you can enjoy the fruits of your labor. This card asks you to appreciate what you have and to share your abundance with others.",
    reversed: "When reversed, the Nine of Cups shows that material satisfaction is not bringing the happiness you expected. Inner fulfillment is more important than outward success.",
    description: "A well-dressed man sits on a bench, arms crossed, with a satisfied smile. Behind him, nine golden cups are arranged on a curved shelf, like trophies. His posture and expression radiate contentment and self-satisfaction.",
    wisdomMessage: "Your wish is granted — enjoy it.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_09_nine_5ba5da68.jpg",
  },
  {
    id: "cups_10_ten",
    name: "Ten of Cups",
    number: "10",
    suit: "Cups",
    element: "Water",
    keywords: ["Harmony", "Happy Family", "Fulfillment", "Bliss", "Lasting Joy"],
    upright: "The Ten of Cups represents the ultimate fulfillment of emotional and family life. This is a card of lasting happiness, harmony, and love. A family stands together, arms raised in joy, as a rainbow of cups arches above them. This card heralds a time of deep contentment and the realization of your heart's deepest wishes.",
    reversed: "When reversed, the Ten of Cups shows family discord or an inability to appreciate the happiness that surrounds you. There may be unrealistic expectations about what happiness should look like.",
    description: "A couple stands with arms raised, looking at a rainbow of ten cups arching across the sky. Two children dance nearby, and in the background, a house and trees suggest a peaceful home. The scene radiates pure joy and familial bliss.",
    wisdomMessage: "True happiness is found in love and connection.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_10_ten_01072a4a.jpg",
  },
  {
    id: "cups_11_page",
    name: "Page of Cups",
    number: "Page",
    suit: "Cups",
    element: "Water",
    keywords: ["Creativity", "Intuition", "New Messages", "Sensitivity", "Imagination"],
    upright: "The Page of Cups brings messages of love and creative inspiration. This young person is sensitive, imaginative, and in touch with their emotions. They may bring news of a new relationship or creative opportunity. This card also suggests a time to nurture your own creativity and emotional intelligence.",
    reversed: "When reversed, the Page of Cups can indicate emotional immaturity, creative blocks, or unreliable news.",
    description: "A young page stands by the sea, holding a cup from which a fish unexpectedly emerges. The page looks at the fish with curiosity and wonder, suggesting the unexpected nature of creative inspiration and intuitive messages.",
    wisdomMessage: "Stay open to unexpected inspiration.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_11_page_860088fb.jpg",
  },
  {
    id: "cups_12_knight",
    name: "Knight of Cups",
    number: "Knight",
    suit: "Cups",
    element: "Water",
    keywords: ["Romance", "Charm", "Idealism", "Artistic", "Following the Heart"],
    upright: "The Knight of Cups is the romantic idealist, riding forth on a quest for love and beauty. This knight follows his heart and is guided by his emotions. He may represent a romantic suitor or a creative invitation. This card asks you to pursue what moves you emotionally and artistically.",
    reversed: "When reversed, the Knight of Cups can indicate moodiness, unreliability, or a tendency to be led astray by fantasies.",
    description: "A knight rides a white horse at a gentle pace, holding a golden cup as if making an offering. His helmet and boots are adorned with wings, suggesting the flight of imagination. He moves with grace and purpose, guided by his heart.",
    wisdomMessage: "Follow your heart on the quest for beauty.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_12_knight_f88afdad.jpg",
  },
  {
    id: "cups_13_queen",
    name: "Queen of Cups",
    number: "Queen",
    suit: "Cups",
    element: "Water",
    keywords: ["Compassion", "Intuition", "Emotional Intelligence", "Nurturing", "Psychic"],
    upright: "The Queen of Cups is the most emotionally intelligent and intuitive of all the court cards. She is deeply compassionate, empathetic, and in tune with the emotional undercurrents around her. She represents a time to trust your intuition, to nurture others and yourself, and to honor your emotional wisdom.",
    reversed: "When reversed, the Queen of Cups can indicate emotional manipulation, codependency, or being overwhelmed by emotions.",
    description: "The Queen sits on a throne at the water's edge, holding an ornate, lidded cup — the most elaborate cup in the tarot. She gazes at it with deep contemplation. Her throne is decorated with sea creatures, and the sea stretches behind her.",
    wisdomMessage: "Trust the wisdom of your heart.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_13_queen_6d3aa6e7.jpg",
  },
  {
    id: "cups_14_king",
    name: "King of Cups",
    number: "King",
    suit: "Cups",
    element: "Water",
    keywords: ["Emotional Balance", "Compassion", "Diplomacy", "Wisdom", "Calm"],
    upright: "The King of Cups represents emotional mastery and wisdom. He is compassionate, diplomatic, and able to navigate complex emotional situations with grace. He represents a mature, emotionally balanced individual who leads with his heart while maintaining his composure. This card asks you to embody these qualities in your own life.",
    reversed: "When reversed, the King of Cups can indicate emotional manipulation, moodiness, or using emotional intelligence for selfish ends.",
    description: "The King sits on a stone throne in the middle of the sea, wearing a blue tunic and a gold crown. He holds a cup and a scepter. Despite the turbulent sea around him, he remains calm and composed, a fish jumping on one side and a ship sailing on the other.",
    wisdomMessage: "Lead with compassion and wisdom.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/cups_14_king_98eb1523.jpg",
  },

  // ═══════════════════════════════════════
  // SUIT OF PENTACLES (Earth / Material)
  // ═══════════════════════════════════════
  {
    id: "pents_01_ace",
    name: "Ace of Pentacles",
    number: "Ace",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["New Opportunity", "Prosperity", "Abundance", "Security", "Manifestation"],
    upright: "The Ace of Pentacles heralds a new financial or material opportunity. A new job, business venture, or investment may be on the horizon. This is a time of material abundance and the potential for lasting prosperity. The ace asks you to seize this opportunity with both hands and to build something of lasting value.",
    reversed: "When reversed, the Ace of Pentacles shows missed opportunities or financial instability. A promising venture may not materialize as expected.",
    description: "A hand emerges from a cloud, offering a large golden pentacle. Below, a garden path leads through an archway of roses to mountains beyond. The scene suggests that material prosperity is available to those who are willing to cultivate it.",
    wisdomMessage: "Seize this opportunity to build lasting prosperity.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_01_ace_ed8e8706.jpg",
  },
  {
    id: "pents_02_two",
    name: "Two of Pentacles",
    number: "2",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Balance", "Adaptability", "Time Management", "Juggling", "Flexibility"],
    upright: "The Two of Pentacles shows the need to balance multiple priorities and manage your resources wisely. You may be juggling work and personal life, or managing finances carefully. This card asks you to stay flexible and adaptable, finding the rhythm that allows you to keep all your balls in the air.",
    reversed: "When reversed, the Two of Pentacles shows that the juggling act is becoming unsustainable. You may be overwhelmed by competing demands.",
    description: "A young man dances while juggling two pentacles connected by an infinity loop. In the background, two ships ride the waves of a turbulent sea. His easy smile suggests he is comfortable with the balancing act.",
    wisdomMessage: "Find your rhythm in the dance of life.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_02_two_b75dcce7.jpg",
  },
  {
    id: "pents_03_three",
    name: "Three of Pentacles",
    number: "3",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Teamwork", "Skill", "Collaboration", "Learning", "Achievement"],
    upright: "The Three of Pentacles represents skilled work, teamwork, and the rewards of mastery. This card shows a craftsman at work, receiving feedback from two advisors. It speaks to the importance of collaboration, learning from others, and taking pride in your craft. Your skills are being recognized and rewarded.",
    reversed: "When reversed, the Three of Pentacles can indicate poor teamwork, lack of effort, or skills that are not being fully utilized.",
    description: "A young craftsman works on a cathedral, while two figures — a monk and a nobleman — consult architectural plans. The craftsman stands on a bench, carving three pentacles into the stone arch. The scene represents the collaboration between vision and skilled execution.",
    wisdomMessage: "Master your craft and collaborate with others.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_03_three_3cf98841.jpg",
  },
  {
    id: "pents_04_four",
    name: "Four of Pentacles",
    number: "4",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Security", "Control", "Stability", "Conservatism", "Possessiveness"],
    upright: "The Four of Pentacles shows a desire for security and control over material resources. You may be holding tightly to what you have, afraid to let go or take risks. While financial stability is important, this card asks you to examine whether your attachment to material things is preventing you from experiencing greater abundance and joy.",
    reversed: "When reversed, the Four of Pentacles shows a release of material attachment and a willingness to share your resources more freely.",
    description: "A crowned figure sits with arms wrapped around a large pentacle, one pentacle balanced on his crown, and one under each foot. Behind him, a city is visible. His posture is defensive and possessive, suggesting an excessive attachment to material security.",
    wisdomMessage: "Security is found within, not in possessions.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_04_four_400d8374.jpg",
  },
  {
    id: "pents_05_five",
    name: "Five of Pentacles",
    number: "5",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Hardship", "Poverty", "Isolation", "Worry", "Spiritual Poverty"],
    upright: "The Five of Pentacles represents material hardship, financial difficulty, or a sense of being left out in the cold. Two figures struggle through the snow, passing a lit church window — help is available, but they may not be aware of it or may feel too proud to ask. This card asks you to seek support and to remember that hardship is temporary.",
    reversed: "When reversed, the Five of Pentacles shows recovery from hardship and the beginning of a more stable period.",
    description: "Two figures — one on crutches, one in rags — trudge through the snow past a church window with a pentacle design. The warm light of the church is visible, but they pass by without entering. The scene speaks to physical and spiritual poverty.",
    wisdomMessage: "Help is available — ask for it.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_05_five_8f90f28d.jpg",
  },
  {
    id: "pents_06_six",
    name: "Six of Pentacles",
    number: "6",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Generosity", "Charity", "Giving", "Receiving", "Balance"],
    upright: "The Six of Pentacles represents generosity, charity, and the balanced exchange of resources. A wealthy merchant gives coins to those in need, holding scales to ensure fair distribution. This card asks you to be generous with your resources and to accept help when it is offered. The flow of giving and receiving creates abundance for all.",
    reversed: "When reversed, the Six of Pentacles can indicate strings-attached giving, inequality, or taking advantage of others' generosity.",
    description: "A wealthy merchant in red robes holds scales in one hand and distributes coins to two kneeling beggars with the other. The scales suggest fairness and balance in the distribution of wealth.",
    wisdomMessage: "Give freely and receive graciously.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_06_six_c4050e75.jpg",
  },
  {
    id: "pents_07_seven",
    name: "Seven of Pentacles",
    number: "7",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Patience", "Investment", "Long-term Vision", "Perseverance", "Assessment"],
    upright: "The Seven of Pentacles shows a time of patient waiting and assessment. You have worked hard and invested your energy, and now you pause to evaluate your progress. This card asks you to be patient — the harvest is coming, but it takes time. Trust the process and continue to tend your garden.",
    reversed: "When reversed, the Seven of Pentacles can indicate impatience, poor investment decisions, or a lack of long-term planning.",
    description: "A young farmer leans on his hoe, contemplating seven pentacles growing on a vine. He has worked hard and is pausing to assess his progress. His posture suggests both weariness and hope as he waits for the harvest.",
    wisdomMessage: "Patient cultivation yields the richest harvest.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_07_seven_a6cc7584.jpg",
  },
  {
    id: "pents_08_eight",
    name: "Eight of Pentacles",
    number: "8",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Diligence", "Skill Development", "Craftsmanship", "Dedication", "Mastery"],
    upright: "The Eight of Pentacles is the card of the dedicated craftsman. You are honing your skills through focused practice and attention to detail. This is a time to commit to your craft, to learn and improve, and to take pride in the quality of your work. Mastery comes through repetition and dedication.",
    reversed: "When reversed, the Eight of Pentacles can indicate a lack of focus, poor workmanship, or skills that are not being properly developed.",
    description: "A craftsman sits at his workbench, carefully carving pentacles. Six completed pentacles hang on a post beside him, and he works on a seventh. In the distance, a town is visible. His focused attention and dedication speak to the value of skilled work.",
    wisdomMessage: "Mastery is achieved through dedicated practice.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_08_eight_1a2e4dfd.jpg",
  },
  {
    id: "pents_09_nine",
    name: "Nine of Pentacles",
    number: "9",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Abundance", "Independence", "Self-sufficiency", "Luxury", "Achievement"],
    upright: "The Nine of Pentacles represents material abundance, independence, and the enjoyment of the fruits of your labor. A woman stands in a lush garden, surrounded by pentacles and a falcon on her wrist. This card celebrates self-sufficiency and the ability to enjoy the good things in life that you have earned through your own efforts.",
    reversed: "When reversed, the Nine of Pentacles can indicate financial dependence, overindulgence, or a hollow sense of success.",
    description: "An elegantly dressed woman stands in a vineyard, her hand resting on a hooded falcon. Nine pentacles hang from the vines around her. Her garden is lush and abundant, and her posture radiates quiet confidence and self-possession.",
    wisdomMessage: "Enjoy the abundance you have created.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_09_nine_45c0ae3f.jpg",
  },
  {
    id: "pents_10_ten",
    name: "Ten of Pentacles",
    number: "10",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Legacy", "Family", "Wealth", "Stability", "Tradition"],
    upright: "The Ten of Pentacles represents lasting wealth, family legacy, and the security of established traditions. An elderly patriarch sits with his family and dogs, surrounded by ten pentacles arranged in the kabbalistic Tree of Life pattern. This card speaks to the importance of building something that will endure beyond your own lifetime.",
    reversed: "When reversed, the Ten of Pentacles can indicate family conflict, financial instability, or the breakdown of traditions.",
    description: "An old man sits with two dogs while a couple and child stand nearby in an archway. Ten pentacles are arranged in the pattern of the Tree of Life. The scene represents the fullness of material and family life across generations.",
    wisdomMessage: "Build a legacy that endures.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_10_ten_45b58895.jpg",
  },
  {
    id: "pents_11_page",
    name: "Page of Pentacles",
    number: "Page",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Ambition", "Study", "New Opportunity", "Practicality", "Diligence"],
    upright: "The Page of Pentacles is the student and the apprentice, eager to learn and apply practical skills. This card heralds new opportunities for study, training, or the beginning of a practical project. The page holds a pentacle aloft, studying it with focused attention. This is a time to be diligent, practical, and open to learning.",
    reversed: "When reversed, the Page of Pentacles can indicate procrastination, lack of focus, or unrealistic expectations about practical matters.",
    description: "A young page stands in a field of flowers, holding a golden pentacle aloft and gazing at it with intense concentration. Mountains rise in the background. His posture suggests both ambition and the careful, methodical approach of an earth sign.",
    wisdomMessage: "Apply yourself diligently to your studies.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_11_page_22660629.jpg",
  },
  {
    id: "pents_12_knight",
    name: "Knight of Pentacles",
    number: "Knight",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Hard Work", "Reliability", "Patience", "Thoroughness", "Commitment"],
    upright: "The Knight of Pentacles is the most reliable and methodical of all the knights. He moves slowly but surely, committed to seeing his tasks through to completion. This knight represents hard work, patience, and the willingness to do what is necessary to achieve your goals. He may not be the most exciting knight, but he is the most dependable.",
    reversed: "When reversed, the Knight of Pentacles can indicate stubbornness, inflexibility, or being stuck in a rut.",
    description: "A knight sits motionless on a heavy black horse in a plowed field. He holds a pentacle in both hands, studying it carefully. Unlike the other knights who are in motion, this knight is still — suggesting patience, reliability, and methodical planning.",
    wisdomMessage: "Steady, reliable effort achieves lasting results.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_12_knight_3a2b36e2.jpg",
  },
  {
    id: "pents_13_queen",
    name: "Queen of Pentacles",
    number: "Queen",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Nurturing", "Practical", "Abundance", "Security", "Down-to-earth"],
    upright: "The Queen of Pentacles is the earth mother — practical, nurturing, and abundantly generous. She creates a warm, secure home and manages her resources with wisdom and care. This card asks you to embody these qualities: to be practical and grounded, to nurture yourself and others, and to create abundance through careful stewardship.",
    reversed: "When reversed, the Queen of Pentacles can indicate neglect of domestic responsibilities, financial mismanagement, or smothering behavior.",
    description: "The Queen sits on a throne decorated with fruit and goats, holding a golden pentacle in her lap. A rabbit runs at her feet, and flowers bloom around her. Her gaze is directed downward at the pentacle, suggesting her focus on the material world and her responsibilities.",
    wisdomMessage: "Nurture your garden and it will flourish.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_13_queen_d24f3508.jpg",
  },
  {
    id: "pents_14_king",
    name: "King of Pentacles",
    number: "King",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Abundance", "Security", "Ambition", "Reliability", "Prosperity"],
    upright: "The King of Pentacles represents material mastery, financial security, and the ability to build and maintain lasting prosperity. He is a successful businessman, a reliable provider, and a wise steward of resources. This card asks you to embody these qualities: to be practical, reliable, and focused on building lasting security.",
    reversed: "When reversed, the King of Pentacles can indicate financial mismanagement, greed, or an excessive focus on material wealth at the expense of other values.",
    description: "The King sits on a throne decorated with bulls and vines, surrounded by a lush garden. He wears robes covered in grapes and holds a scepter and a golden pentacle. His posture radiates confidence, security, and material mastery.",
    wisdomMessage: "Build your kingdom with patience and wisdom.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/pents_14_king_fc94bc9d.jpg",
  },

  // ═══════════════════════════════════════
  // SUIT OF SWORDS (Air / Intellect)
  // ═══════════════════════════════════════
  {
    id: "swords_01_ace",
    name: "Ace of Swords",
    number: "Ace",
    suit: "Swords",
    element: "Air",
    keywords: ["Clarity", "Truth", "Breakthrough", "New Ideas", "Mental Force"],
    upright: "The Ace of Swords heralds a breakthrough in thinking, a moment of clarity, or the beginning of a new intellectual pursuit. The sword cuts through confusion and illusion, revealing the truth. This is a time to speak your truth, to make clear decisions, and to pursue justice. The mind is sharp and ready for new challenges.",
    reversed: "When reversed, the Ace of Swords shows confusion, miscommunication, or a decision that is not well thought out.",
    description: "A hand emerges from a cloud, holding a sword upright. A crown adorned with a laurel wreath and palm branch hangs from the sword's tip. Mountains rise in the background. The scene represents the power of the mind to cut through confusion and reveal truth.",
    wisdomMessage: "Speak your truth with clarity and courage.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_01_ace_2392f1c8.jpg",
  },
  {
    id: "swords_02_two",
    name: "Two of Swords",
    number: "2",
    suit: "Swords",
    element: "Air",
    keywords: ["Indecision", "Stalemate", "Blocked Emotions", "Avoidance", "Choices"],
    upright: "The Two of Swords represents a stalemate or a difficult decision that you are avoiding. A blindfolded woman holds two crossed swords, unable to see clearly. This card asks you to remove the blindfold and face the situation honestly. The decision you are avoiding will not resolve itself — you must choose.",
    reversed: "When reversed, the Two of Swords shows that the stalemate is breaking and a decision is being made, though it may be difficult.",
    description: "A blindfolded woman sits before a calm sea, holding two crossed swords. A crescent moon is visible in the sky. Her posture is defensive and closed, suggesting an unwillingness to face a difficult situation.",
    wisdomMessage: "Remove the blindfold and face your choices.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_02_two_b5ce102d.jpg",
  },
  {
    id: "swords_03_three",
    name: "Three of Swords",
    number: "3",
    suit: "Swords",
    element: "Air",
    keywords: ["Heartbreak", "Sorrow", "Grief", "Separation", "Pain"],
    upright: "The Three of Swords is one of the most direct cards in the tarot — three swords pierce a heart against a stormy sky. This card represents heartbreak, grief, and the pain of separation or loss. While the pain is real, this card also reminds you that storms pass and healing is possible. Acknowledge your pain and allow yourself to grieve.",
    reversed: "When reversed, the Three of Swords shows that the worst of the pain is over and healing is beginning.",
    description: "Three swords pierce a red heart against a stormy, cloud-filled sky. The image is stark and direct — there is no softening of the message. Rain falls, adding to the sense of grief and sorrow.",
    wisdomMessage: "Allow yourself to grieve — healing will follow.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_03_three_bc9c1810.jpg",
  },
  {
    id: "swords_04_four",
    name: "Four of Swords",
    number: "4",
    suit: "Swords",
    element: "Air",
    keywords: ["Rest", "Recovery", "Contemplation", "Retreat", "Healing"],
    upright: "The Four of Swords represents a necessary period of rest and recovery. A knight lies in repose, as if in meditation or sleep. This card asks you to step back from the fray, to rest and recuperate, and to allow your mind and body to heal. This is not a time for action, but for stillness and reflection.",
    reversed: "When reversed, the Four of Swords shows a return to activity after a period of rest, or a restlessness that prevents proper recovery.",
    description: "A knight lies in effigy on a tomb, hands clasped in prayer. Three swords hang on the wall above him, and one lies beneath him. A stained glass window shows a figure in supplication. The scene suggests peaceful rest and recovery.",
    wisdomMessage: "Rest and recover — you will be stronger for it.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_04_four_88b0e31d.jpg",
  },
  {
    id: "swords_05_five",
    name: "Five of Swords",
    number: "5",
    suit: "Swords",
    element: "Air",
    keywords: ["Conflict", "Defeat", "Hollow Victory", "Betrayal", "Tension"],
    upright: "The Five of Swords represents conflict, defeat, and the hollow victory that comes from winning at all costs. A figure gathers swords while two others walk away in defeat. This card asks you to consider whether the battle you are fighting is worth the cost, and whether a victory that leaves others feeling humiliated is truly a victory.",
    reversed: "When reversed, the Five of Swords shows a desire to move on from conflict and to seek reconciliation.",
    description: "A smirking figure holds three swords while two others lie on the ground. Two defeated figures walk away in the background, their heads bowed. The sky is stormy and turbulent. The scene suggests a conflict where the winner has gained little of real value.",
    wisdomMessage: "Choose your battles wisely.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_05_five_49e056d3.jpg",
  },
  {
    id: "swords_06_six",
    name: "Six of Swords",
    number: "6",
    suit: "Swords",
    element: "Air",
    keywords: ["Transition", "Moving On", "Calmer Waters", "Recovery", "Travel"],
    upright: "The Six of Swords represents a transition from turbulence to calmer waters. A ferryman guides a woman and child across a river, away from choppy waters toward smoother ones. This card speaks to the gradual process of moving on from difficulty and finding peace. The journey may be slow, but you are heading in the right direction.",
    reversed: "When reversed, the Six of Swords shows resistance to necessary change or a return to a difficult situation.",
    description: "A ferryman poles a boat across a river. A woman and child sit huddled in the bow, surrounded by six upright swords. The water on their side of the boat is choppy, while the far shore is calm. The scene represents a journey from difficulty toward peace.",
    wisdomMessage: "You are moving toward calmer waters.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_06_six_0e5a1b3a.jpg",
  },
  {
    id: "swords_07_seven",
    name: "Seven of Swords",
    number: "7",
    suit: "Swords",
    element: "Air",
    keywords: ["Deception", "Strategy", "Cunning", "Stealth", "Avoidance"],
    upright: "The Seven of Swords represents deception, strategy, and the need to act with cunning. A figure sneaks away from a camp carrying five swords, leaving two behind. This card can indicate that someone is being deceptive, or that you need to use strategy and tact rather than direct confrontation. It can also suggest that you are avoiding a situation that needs to be faced.",
    reversed: "When reversed, the Seven of Swords shows that deception is being uncovered or that you are choosing a more honest approach.",
    description: "A figure tiptoes away from a military camp, carrying five swords and looking back over his shoulder. Two swords remain planted in the ground. The scene suggests stealth, strategy, and possibly deception.",
    wisdomMessage: "Be strategic, but not at the cost of your integrity.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_07_seven_36a53896.jpg",
  },
  {
    id: "swords_08_eight",
    name: "Eight of Swords",
    number: "8",
    suit: "Swords",
    element: "Air",
    keywords: ["Restriction", "Imprisonment", "Powerlessness", "Victim Mentality", "Fear"],
    upright: "The Eight of Swords represents a feeling of restriction and powerlessness. A blindfolded woman stands bound, surrounded by eight swords. However, the swords are not touching her, and the bindings are loose — she could free herself if she chose. This card asks you to examine whether the restrictions you feel are real or self-imposed.",
    reversed: "When reversed, the Eight of Swords shows liberation from self-imposed restrictions and a new sense of freedom.",
    description: "A blindfolded woman stands bound in a marshy area, surrounded by eight swords planted in the ground. The swords form a loose cage around her, but none touch her. In the background, a castle is visible on a cliff.",
    wisdomMessage: "The cage is of your own making — you can leave.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_08_eight_8fbfdc6f.jpg",
  },
  {
    id: "swords_09_nine",
    name: "Nine of Swords",
    number: "9",
    suit: "Swords",
    element: "Air",
    keywords: ["Anxiety", "Nightmares", "Worry", "Despair", "Mental Anguish"],
    upright: "The Nine of Swords represents anxiety, nightmares, and the torment of a troubled mind. A figure sits up in bed, head in hands, while nine swords hang on the wall above. This card often appears when worry and anxiety are at their peak, and things seem worse than they actually are. The darkness of the night always gives way to dawn.",
    reversed: "When reversed, the Nine of Swords shows that the worst of the anxiety is passing and a more hopeful perspective is emerging.",
    description: "A figure sits up in bed, covering their face with their hands in despair. Nine swords hang horizontally on the wall above. The bedcover is decorated with roses and astrological symbols. The scene captures the anguish of sleepless nights and anxious thoughts.",
    wisdomMessage: "The darkest hour is just before dawn.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_09_nine_877ed8e9.jpg",
  },
  {
    id: "swords_10_ten",
    name: "Ten of Swords",
    number: "10",
    suit: "Swords",
    element: "Air",
    keywords: ["Endings", "Defeat", "Rock Bottom", "Betrayal", "New Dawn"],
    upright: "The Ten of Swords represents a painful ending — a defeat, a betrayal, or hitting rock bottom. A figure lies face down with ten swords in his back. While this is one of the most dramatic cards in the tarot, it also carries a message of hope: the sun is rising on the horizon. Every ending is also a beginning, and from this low point, the only way is up.",
    reversed: "When reversed, the Ten of Swords shows recovery from a devastating experience and the beginning of a new cycle.",
    description: "A figure lies face down on the ground, ten swords planted in his back. The sky above is dark and stormy, but on the horizon, the sun is beginning to rise. The sea is calm. The scene represents the absolute end of a difficult cycle.",
    wisdomMessage: "The sun rises even after the darkest night.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_10_ten_0bc96573.jpg",
  },
  {
    id: "swords_11_page",
    name: "Page of Swords",
    number: "Page",
    suit: "Swords",
    element: "Air",
    keywords: ["Curiosity", "Vigilance", "Mental Agility", "New Ideas", "Communication"],
    upright: "The Page of Swords is quick-witted, curious, and mentally agile. This young person is always gathering information and is not afraid to speak their mind. They may bring news or messages that require careful consideration. This card also suggests a time to be vigilant, to gather information before acting, and to approach situations with intellectual curiosity.",
    reversed: "When reversed, the Page of Swords can indicate gossip, hasty communication, or using information to manipulate others.",
    description: "A young page stands on a hilltop, holding a sword aloft. The wind blows his hair and the clouds move swiftly behind him. His posture is alert and watchful, suggesting vigilance and readiness.",
    wisdomMessage: "Gather information before acting.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_11_page_509289cf.jpg",
  },
  {
    id: "swords_12_knight",
    name: "Knight of Swords",
    number: "Knight",
    suit: "Swords",
    element: "Air",
    keywords: ["Action", "Ambition", "Drive", "Courage", "Impulsiveness"],
    upright: "The Knight of Swords charges forward with fierce determination and intellectual courage. He is the most action-oriented of all the knights, moving at full speed toward his goal. This card asks you to act with courage and decisiveness, but also to consider the consequences of your actions before charging ahead.",
    reversed: "When reversed, the Knight of Swords can indicate recklessness, aggression, or a tendency to act without thinking.",
    description: "A knight charges forward on a white horse, sword raised high. The wind whips his cloak and the horse's mane. Storm clouds gather behind him. His expression is fierce and determined, suggesting single-minded purpose.",
    wisdomMessage: "Act with courage, but temper it with wisdom.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_12_knight_6a538194.jpg",
  },
  {
    id: "swords_13_queen",
    name: "Queen of Swords",
    number: "Queen",
    suit: "Swords",
    element: "Air",
    keywords: ["Independence", "Clarity", "Perception", "Honesty", "Directness"],
    upright: "The Queen of Swords is the most perceptive and direct of all the court cards. She sees through illusion and speaks the truth, even when it is uncomfortable. She represents a time to think clearly, to set aside emotion and see the situation as it truly is. Her sword cuts through confusion, and her judgment is fair and honest.",
    reversed: "When reversed, the Queen of Swords can indicate cruelty, bitterness, or using intelligence to wound others.",
    description: "The Queen sits on a stone throne decorated with butterflies and an angel, holding her sword upright. One hand is raised in greeting or blessing. The sky is partly cloudy, and the wind blows through the trees. Her expression is serious and direct.",
    wisdomMessage: "See clearly and speak your truth.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_13_queen_88115939.jpg",
  },
  {
    id: "swords_14_king",
    name: "King of Swords",
    number: "King",
    suit: "Swords",
    element: "Air",
    keywords: ["Authority", "Intellect", "Truth", "Justice", "Ethics"],
    upright: "The King of Swords represents intellectual authority, clear thinking, and the ability to make fair and just decisions. He is a master of logic and reason, and his judgments are based on truth rather than emotion. This card asks you to approach your situation with clarity, objectivity, and ethical integrity.",
    reversed: "When reversed, the King of Swords can indicate tyranny, manipulation, or the misuse of intellectual power.",
    description: "The King sits on a stone throne decorated with butterflies and crescent moons, holding his sword upright. His gaze is direct and penetrating. The sky is partly cloudy, suggesting that while clarity is available, there are still complexities to navigate.",
    wisdomMessage: "Lead with clarity, justice, and integrity.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/swords_14_king_e2e05db3.jpg",
  },

  // ═══════════════════════════════════════
  // SUIT OF WANDS (Fire / Passion)
  // ═══════════════════════════════════════
  {
    id: "wands_01_ace",
    name: "Ace of Wands",
    number: "Ace",
    suit: "Wands",
    element: "Fire",
    keywords: ["New Beginnings", "Inspiration", "Passion", "Creative Force", "Potential"],
    upright: "The Ace of Wands heralds a burst of creative energy, inspiration, and new beginnings. A hand emerges from a cloud, offering a sprouting wand — the spark of a new idea or project. This is a time to act on your inspiration, to begin new ventures with enthusiasm, and to trust the creative fire within you.",
    reversed: "When reversed, the Ace of Wands shows creative blocks, delays, or a lack of motivation.",
    description: "A hand emerges from a cloud, holding a wand from which leaves are sprouting. Mountains and a castle are visible in the background. The scene represents the raw creative energy and potential of the element of fire.",
    wisdomMessage: "Act on your inspiration now.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_01_ace_e05402b9.jpg",
  },
  {
    id: "wands_02_two",
    name: "Two of Wands",
    number: "2",
    suit: "Wands",
    element: "Fire",
    keywords: ["Planning", "Future Vision", "Progress", "Decisions", "Discovery"],
    upright: "The Two of Wands represents a moment of planning and looking toward the future. A figure stands on a castle wall, holding a globe and gazing out at the horizon. The world is at your feet — this card asks you to dream big, to plan your next move, and to consider the possibilities that lie ahead.",
    reversed: "When reversed, the Two of Wands shows fear of the unknown or an inability to plan effectively.",
    description: "A figure stands on a castle battlements, holding a small globe in one hand and a wand in the other. A second wand is fixed to the wall beside him. He gazes out at the sea and mountains, contemplating his next move.",
    wisdomMessage: "The world is at your feet — dare to dream.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_02_two_3909c057.jpg",
  },
  {
    id: "wands_03_three",
    name: "Three of Wands",
    number: "3",
    suit: "Wands",
    element: "Fire",
    keywords: ["Expansion", "Foresight", "Progress", "Enterprise", "Exploration"],
    upright: "The Three of Wands represents expansion, foresight, and the first results of your efforts. A figure stands on a cliff, watching ships sail out to sea. Your plans are in motion and the results are beginning to manifest. This card encourages you to think big, to expand your horizons, and to embrace the adventure of new territories.",
    reversed: "When reversed, the Three of Wands shows delays, setbacks, or a lack of foresight.",
    description: "A figure stands with his back to us on a cliff, watching three ships sail across the sea. Three wands are planted in the ground around him. The scene suggests a merchant or explorer watching his ventures set sail.",
    wisdomMessage: "Your ventures are setting sail — trust the journey.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_03_three_65f65e59.jpg",
  },
  {
    id: "wands_04_four",
    name: "Four of Wands",
    number: "4",
    suit: "Wands",
    element: "Fire",
    keywords: ["Celebration", "Harmony", "Home", "Community", "Completion"],
    upright: "The Four of Wands is a card of celebration, harmony, and the joy of community. Four wands form a canopy decorated with flowers and fruit, under which figures celebrate. This card heralds a time of festivity, homecoming, and the completion of a phase of work. It is time to celebrate your achievements with those you love.",
    reversed: "When reversed, the Four of Wands can indicate a lack of harmony at home or a celebration that is delayed.",
    description: "Four wands are planted in the ground, their tops connected by a garland of flowers and fruit. Two figures dance beneath the canopy, holding bouquets. In the background, a castle is visible and more people celebrate.",
    wisdomMessage: "Celebrate your achievements with those you love.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_04_four_7c40ea25.jpg",
  },
  {
    id: "wands_05_five",
    name: "Five of Wands",
    number: "5",
    suit: "Wands",
    element: "Fire",
    keywords: ["Conflict", "Competition", "Struggle", "Disagreement", "Chaos"],
    upright: "The Five of Wands represents conflict, competition, and the chaos of competing ideas and energies. Five figures wave their wands in apparent conflict, though it is unclear whether they are fighting or playing. This card asks you to channel your competitive energy constructively, to engage with challenges as opportunities for growth.",
    reversed: "When reversed, the Five of Wands shows that conflict is resolving and a more cooperative approach is emerging.",
    description: "Five young men brandish wands at each other in apparent conflict. Their postures suggest both aggression and playfulness — it is unclear whether this is a real fight or a game. The scene represents the energy of competition and conflict.",
    wisdomMessage: "Channel your competitive energy constructively.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_05_five_d4cc5457.jpg",
  },
  {
    id: "wands_06_six",
    name: "Six of Wands",
    number: "6",
    suit: "Wands",
    element: "Fire",
    keywords: ["Victory", "Success", "Public Recognition", "Progress", "Self-confidence"],
    upright: "The Six of Wands is the victory card — a triumphant return after a successful campaign. A rider on a white horse is crowned with a laurel wreath, surrounded by a cheering crowd. This card heralds public recognition, success, and the confidence that comes from achieving your goals. Your hard work is being recognized.",
    reversed: "When reversed, the Six of Wands shows a fall from grace or success that is not being recognized.",
    description: "A rider on a white horse wears a laurel wreath and holds a wand adorned with another wreath. A crowd of people with wands surrounds him in celebration. The scene represents the triumphant return of a hero.",
    wisdomMessage: "Your victory is well-deserved — accept the recognition.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_06_six_262658bc.jpg",
  },
  {
    id: "wands_07_seven",
    name: "Seven of Wands",
    number: "7",
    suit: "Wands",
    element: "Fire",
    keywords: ["Perseverance", "Defensiveness", "Challenge", "Courage", "Standing Firm"],
    upright: "The Seven of Wands represents the courage to stand your ground against opposition. A figure stands on a hilltop, defending himself against six wands being thrust at him from below. This card asks you to hold your position, to defend what you believe in, and to have the courage to stand alone if necessary.",
    reversed: "When reversed, the Seven of Wands shows giving in to pressure or abandoning a position that should be defended.",
    description: "A figure stands on a hilltop, wielding a wand against six others that are thrust at him from below. His stance is defensive but determined. He is outnumbered but holds the high ground.",
    wisdomMessage: "Stand your ground — your position is defensible.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_07_seven_c710ede3.jpg",
  },
  {
    id: "wands_08_eight",
    name: "Eight of Wands",
    number: "8",
    suit: "Wands",
    element: "Fire",
    keywords: ["Speed", "Action", "Movement", "News", "Progress"],
    upright: "The Eight of Wands represents swift action, rapid progress, and the arrival of news or messages. Eight wands fly through the air, moving swiftly toward their destination. This card asks you to act quickly, to embrace the momentum that is available to you, and to expect rapid developments in your situation.",
    reversed: "When reversed, the Eight of Wands shows delays, miscommunication, or scattered energy.",
    description: "Eight wands fly through the air over a peaceful landscape. There are no figures in this card — only the wands in motion. The scene suggests rapid movement, messages in transit, and the swift unfolding of events.",
    wisdomMessage: "Act swiftly — the time for action is now.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_08_eight_22c36e7f.jpg",
  },
  {
    id: "wands_09_nine",
    name: "Nine of Wands",
    number: "9",
    suit: "Wands",
    element: "Fire",
    keywords: ["Resilience", "Persistence", "Defensiveness", "Stamina", "Last Stand"],
    upright: "The Nine of Wands represents resilience, persistence, and the determination to keep going even when you are tired and battle-worn. A figure leans on a wand, looking back over his shoulder with wariness. Eight wands stand behind him like a fence. This card asks you to gather your remaining strength and persevere — you are closer to the finish line than you think.",
    reversed: "When reversed, the Nine of Wands shows exhaustion, giving up, or paranoia.",
    description: "A bandaged figure leans on a wand, looking back over his shoulder with a wary expression. Eight wands stand in a row behind him. His posture suggests both weariness and determination — he has been through a battle but is still standing.",
    wisdomMessage: "Gather your strength — the finish line is near.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_09_nine_efe61394.jpg",
  },
  {
    id: "wands_10_ten",
    name: "Ten of Wands",
    number: "10",
    suit: "Wands",
    element: "Fire",
    keywords: ["Burden", "Responsibility", "Overwhelm", "Hard Work", "Completion"],
    upright: "The Ten of Wands represents the burden of responsibility and the weight of too many commitments. A figure struggles to carry ten wands toward a distant town. This card asks you to examine what you are carrying and whether all of it is truly necessary. It may be time to delegate, to let go of some responsibilities, or to ask for help.",
    reversed: "When reversed, the Ten of Wands shows a release of burdens and a lighter load ahead.",
    description: "A figure struggles forward, bent under the weight of ten wands bundled together. A town is visible in the distance. The figure's posture suggests exhaustion and determination — they are almost there, but the load is heavy.",
    wisdomMessage: "Put down what is not yours to carry.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_10_ten_ecebcb5b.jpg",
  },
  {
    id: "wands_11_page",
    name: "Page of Wands",
    number: "Page",
    suit: "Wands",
    element: "Fire",
    keywords: ["Enthusiasm", "Exploration", "Discovery", "Free Spirit", "New Ideas"],
    upright: "The Page of Wands is the enthusiastic explorer, full of energy and eager to discover new horizons. This young person brings news of exciting opportunities and adventures. They are passionate, creative, and unafraid to try new things. This card asks you to embrace your inner adventurer and to approach life with curiosity and enthusiasm.",
    reversed: "When reversed, the Page of Wands can indicate immaturity, lack of direction, or unreliable news.",
    description: "A young page stands in a desert landscape, holding a wand and gazing at it with fascination. Salamanders decorate his tunic — a symbol of fire. Mountains rise in the background. His posture suggests curiosity and the excitement of discovery.",
    wisdomMessage: "Embrace your inner adventurer.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_11_page_e9568e73.jpg",
  },
  {
    id: "wands_12_knight",
    name: "Knight of Wands",
    number: "Knight",
    suit: "Wands",
    element: "Fire",
    keywords: ["Adventure", "Passion", "Impulsiveness", "Energy", "Travel"],
    upright: "The Knight of Wands is the most adventurous and impulsive of all the knights. He charges forward on a rearing horse, full of passion and enthusiasm. This card asks you to act with courage and to pursue your passions with energy and determination. However, be careful not to act so impulsively that you fail to consider the consequences.",
    reversed: "When reversed, the Knight of Wands can indicate recklessness, scattered energy, or a tendency to start things without finishing them.",
    description: "A knight charges forward on a rearing horse, holding a wand aloft. His armor is decorated with salamanders, and his plume streams behind him. The desert landscape suggests adventure in exotic territories.",
    wisdomMessage: "Pursue your passion with courage and fire.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_12_knight_614ce65b.jpg",
  },
  {
    id: "wands_13_queen",
    name: "Queen of Wands",
    number: "Queen",
    suit: "Wands",
    element: "Fire",
    keywords: ["Confidence", "Independence", "Charisma", "Determination", "Vibrancy"],
    upright: "The Queen of Wands is the most vibrant and charismatic of all the court cards. She radiates confidence, warmth, and creative energy. This card asks you to embody her qualities: to be bold, confident, and passionate in your pursuits. She is independent and self-assured, and her enthusiasm is contagious.",
    reversed: "When reversed, the Queen of Wands can indicate jealousy, manipulation, or a tendency to be domineering.",
    description: "The Queen sits on a throne decorated with lions and sunflowers, holding a wand in one hand and a sunflower in the other. A black cat sits at her feet. Her posture radiates confidence and warmth. She faces forward, engaging directly with the viewer.",
    wisdomMessage: "Radiate confidence and let your passion shine.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_13_queen_a033cd6d.jpg",
  },
  {
    id: "wands_14_king",
    name: "King of Wands",
    number: "King",
    suit: "Wands",
    element: "Fire",
    keywords: ["Leadership", "Vision", "Entrepreneurship", "Charisma", "Honor"],
    upright: "The King of Wands is the visionary leader — charismatic, bold, and full of creative fire. He represents a time to lead with vision and passion, to inspire others with your enthusiasm, and to pursue your goals with the confidence of a natural leader. This card asks you to step into your power and to lead by example.",
    reversed: "When reversed, the King of Wands can indicate arrogance, impulsiveness, or a tendency to dominate rather than inspire.",
    description: "The King sits on a throne decorated with lions and salamanders, holding a wand that is alive with growth. A salamander crawls near his feet. His posture is commanding and confident, and he gazes forward with the vision of a natural leader.",
    wisdomMessage: "Lead with vision, passion, and integrity.",
    imageUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663487115720/2i9JDtoxmfdYJFqXPDfh6d/wands_14_king_155a80af.jpg",
  },
];

export const getSuitCards = (suit: TarotSuit): TarotCard[] =>
  tarotCards.filter((c) => c.suit === suit);

export const getCardById = (id: string): TarotCard | undefined =>
  tarotCards.find((c) => c.id === id);

export const searchCards = (query: string): TarotCard[] => {
  const q = query.toLowerCase().trim();
  if (!q) return tarotCards;
  return tarotCards.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.suit.toLowerCase().includes(q) ||
      c.keywords.some((k) => k.toLowerCase().includes(q)) ||
      c.upright.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q)
  );
};

export const SUITS: TarotSuit[] = ["Major Arcana", "Cups", "Pentacles", "Swords", "Wands"];

export const SUIT_ELEMENTS: Record<TarotSuit, string> = {
  "Major Arcana": "All Elements",
  Cups: "Water — Emotions & Relationships",
  Pentacles: "Earth — Material & Practical",
  Swords: "Air — Intellect & Decisions",
  Wands: "Fire — Passion & Creativity",
};

export const SUIT_COLORS: Record<TarotSuit, string> = {
  "Major Arcana": "#c9a84c",
  Cups: "#4a90d9",
  Pentacles: "#5a8a3c",
  Swords: "#9b59b6",
  Wands: "#e67e22",
};
